# Generated by Django 5.2.10 on 2026-01-16 10:56

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student')], default='student', max_length=10)),
                ('student_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Student ID')),
                ('employee_id', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Employee ID')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Phone Number')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, default='India', max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='Department')),
                ('semester', models.IntegerField(blank=True, null=True, verbose_name='Semester')),
                ('year_of_admission', models.IntegerField(blank=True, null=True, verbose_name='Year of Admission')),
                ('year_of_passing', models.IntegerField(blank=True, null=True, verbose_name='Year of Passing')),
                ('designation', models.CharField(blank=True, max_length=100, verbose_name='Designation')),
                ('qualification', models.CharField(blank=True, max_length=200, verbose_name='Qualification')),
                ('experience', models.IntegerField(blank=True, null=True, verbose_name='Experience (years)')),
                ('specialization', models.CharField(blank=True, max_length=200, verbose_name='Specialization')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Profile Picture')),
                ('face_encoding', models.BinaryField(blank=True, null=True, verbose_name='Face Encoding')),
                ('is_face_registered', models.BooleanField(default=False, verbose_name='Face Registered')),
                ('registration_date', models.DateTimeField(blank=True, null=True, verbose_name='Face Registration Date')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('blood_group', models.CharField(blank=True, max_length=5, verbose_name='Blood Group')),
                ('emergency_contact', models.CharField(blank=True, max_length=15, verbose_name='Emergency Contact')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, verbose_name='Emergency Contact Name')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Department Name')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Department Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('established_date', models.DateField(blank=True, null=True, verbose_name='Established Date')),
                ('total_students', models.IntegerField(default=0, verbose_name='Total Students')),
                ('total_teachers', models.IntegerField(default=0, verbose_name='Total Teachers')),
                ('office_phone', models.CharField(blank=True, max_length=15, verbose_name='Office Phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Department Email')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Location')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hod', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_hod', to=settings.AUTH_USER_MODEL, verbose_name='Head of Department')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=20, unique=True, verbose_name='Roll Number')),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Registration Number')),
                ('batch', models.CharField(max_length=10, verbose_name='Batch (e.g., 2024-2028)')),
                ('section', models.CharField(blank=True, max_length=10, verbose_name='Section')),
                ('current_semester', models.IntegerField(default=1, verbose_name='Current Semester')),
                ('father_name', models.CharField(blank=True, max_length=100, verbose_name="Father's Name")),
                ('mother_name', models.CharField(blank=True, max_length=100, verbose_name="Mother's Name")),
                ('guardian_name', models.CharField(blank=True, max_length=100, verbose_name="Guardian's Name")),
                ('guardian_relation', models.CharField(blank=True, max_length=50, verbose_name='Relation with Guardian')),
                ('guardian_contact', models.CharField(blank=True, max_length=15, verbose_name='Guardian Contact')),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='CGPA')),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Attendance %')),
                ('backlog_count', models.IntegerField(default=0, verbose_name='Backlog Count')),
                ('aadhar_card', models.CharField(blank=True, max_length=12, verbose_name='Aadhar Card Number')),
                ('pan_card', models.CharField(blank=True, max_length=10, verbose_name='PAN Card Number')),
                ('is_hosteller', models.BooleanField(default=False, verbose_name='Hosteller')),
                ('scholarship', models.BooleanField(default=False, verbose_name='Receiving Scholarship')),
                ('scholarship_details', models.TextField(blank=True, verbose_name='Scholarship Details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=20, unique=True, verbose_name='Employee Code')),
                ('department', models.CharField(max_length=100, verbose_name='Department')),
                ('designation', models.CharField(max_length=100, verbose_name='Designation')),
                ('highest_qualification', models.CharField(max_length=100, verbose_name='Highest Qualification')),
                ('qualification_details', models.TextField(blank=True, verbose_name='Qualification Details')),
                ('specialization', models.CharField(max_length=200, verbose_name='Specialization')),
                ('total_experience', models.IntegerField(verbose_name='Total Experience (Years)')),
                ('previous_institution', models.CharField(blank=True, max_length=200, verbose_name='Previous Institution')),
                ('joining_date', models.DateField(verbose_name='Joining Date')),
                ('office_phone', models.CharField(blank=True, max_length=15, verbose_name='Office Phone')),
                ('extension', models.CharField(blank=True, max_length=10, verbose_name='Extension')),
                ('office_location', models.CharField(blank=True, max_length=100, verbose_name='Office Location')),
                ('is_hod', models.BooleanField(default=False, verbose_name='Head of Department')),
                ('hod_department', models.CharField(blank=True, max_length=100, verbose_name='HOD Department')),
                ('is_class_coordinator', models.BooleanField(default=False, verbose_name='Class Coordinator')),
                ('coordinator_class', models.CharField(blank=True, max_length=50, verbose_name='Coordinator Class')),
                ('aadhar_card', models.CharField(blank=True, max_length=12, verbose_name='Aadhar Card Number')),
                ('pan_card', models.CharField(blank=True, max_length=10, verbose_name='PAN Card Number')),
                ('bank_account', models.CharField(blank=True, max_length=20, verbose_name='Bank Account Number')),
                ('ifsc_code', models.CharField(blank=True, max_length=11, verbose_name='IFSC Code')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('leave_balance', models.IntegerField(default=30, verbose_name='Leave Balance (Days)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Profile',
                'verbose_name_plural': 'Teacher Profiles',
            },
        ),
    ]
