# Generated by Django 5.2.12 on 2026-03-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_studentprofile_student_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='employee_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Employee Name'),
        ),
    ]
