# Generated by Django 5.2.12 on 2026-03-10 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_teacherprofile_employee_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='student_name',
            new_name='user_full_name',
        ),
        migrations.RenameField(
            model_name='teacherprofile',
            old_name='employee_name',
            new_name='user_full_name',
        ),
    ]
