# Generated by Django 5.2.12 on 2026-03-10 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_student_name_studentprofile_user_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
    ]
