# Generated by Django 5.2.12 on 2026-03-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_studentprofile_aadhar_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='user_full_name',
            field=models.CharField(max_length=100, verbose_name='Student Name'),
        ),
    ]
