# Generated by Django 5.2.12 on 2026-06-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_studentprofile_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='batch',
            field=models.CharField(max_length=10, verbose_name='Batch (e.g., 2026-2030)'),
        ),
    ]
