# Generated by Django 5.2.12 on 2026-03-10 08:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceimage',
            name='image',
            field=models.ImageField(upload_to='faces', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
