# Generated by Django 5.2.12 on 2026-06-23 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_app', '0002_alter_faceimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faceimage',
            old_name='person',
            new_name='person_id',
        ),
        migrations.RenameField(
            model_name='recognitionlog',
            old_name='person',
            new_name='person_id',
        ),
    ]
