# Generated by Django 5.2.10 on 2026-01-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('time_in', models.TimeField(verbose_name='Check-in Time')),
                ('time_out', models.TimeField(blank=True, null=True, verbose_name='Check-out Time')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='Duration')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half Day'), ('leave', 'Leave'), ('od', 'On Duty')], default='present', max_length=20)),
                ('reason', models.TextField(blank=True, verbose_name='Reason for Absence/Late')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('face_image', models.ImageField(blank=True, null=True, upload_to='attendance_images/', verbose_name='Face Image')),
                ('confidence_score', models.FloatField(blank=True, null=True, verbose_name='Confidence Score')),
                ('face_match_duration', models.FloatField(blank=True, null=True, verbose_name='Face Match Duration (ms)')),
                ('device_id', models.CharField(blank=True, max_length=100, verbose_name='Device ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Location')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date', '-time_in'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('attempt', 'Attempt'), ('success', 'Success'), ('failure', 'Failure'), ('retry', 'Retry')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('image_path', models.CharField(blank=True, max_length=500)),
                ('device_id', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Attendance Log',
                'verbose_name_plural': 'Attendance Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20, unique=True, verbose_name='Course Code')),
                ('course_name', models.CharField(max_length=200, verbose_name='Course Name')),
                ('course_type', models.CharField(choices=[('core', 'Core'), ('elective', 'Elective'), ('lab', 'Lab'), ('project', 'Project'), ('seminar', 'Seminar')], default='core', max_length=20)),
                ('semester', models.IntegerField(verbose_name='Semester')),
                ('credits', models.IntegerField(default=3, verbose_name='Credits')),
                ('schedule', models.CharField(max_length=100, verbose_name='Schedule (e.g., Mon-Wed-Fri 10:00-11:30)')),
                ('room', models.CharField(max_length=50, verbose_name='Room Number')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('description', models.TextField(blank=True, verbose_name='Course Description')),
                ('objectives', models.TextField(blank=True, verbose_name='Course Objectives')),
                ('prerequisites', models.CharField(blank=True, max_length=200, verbose_name='Prerequisites')),
                ('total_hours', models.IntegerField(default=45, verbose_name='Total Hours')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('max_strength', models.IntegerField(default=60, verbose_name='Maximum Strength')),
                ('current_strength', models.IntegerField(default=0, verbose_name='Current Strength')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'ordering': ['course_code'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='Enrollment Date')),
                ('enrollment_type', models.CharField(choices=[('regular', 'Regular'), ('audit', 'Audit'), ('credit', 'Credit')], default='regular', max_length=20)),
                ('grade', models.CharField(blank=True, max_length=2, verbose_name='Grade')),
                ('marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Marks')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Enrollment',
                'verbose_name_plural': 'Enrollments',
                'ordering': ['-enrollment_date'],
            },
        ),
    ]
