# Generated by Django 5.2.12 on 2026-04-02 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_course_end_date_alter_course_start_date'),
        ('users', '0008_alter_studentprofile_user_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='users.department'),
        ),
    ]
